---
output: github_document
bibliography: /home/fos085/zoteroFiles/JabRefPDF//SDFReferences.bib
csl: /home/fos085/ABARES/RISDM_MS//ecography.csl
---

## RISDM is an R package that provides functionality for estimating, diagnosing, predicting and interpreting Integrated Species Distribution Models. These models take data from disparate sources and utilises their best attributes whilst minimising their worst.

## Summary

At its very base, the \texttt{RISDM} package implements the models described in [@mil19;@fle19;@isa20]. These models exploit multiple data types into a single species distribution model. Such models coherently capture uncertainty throughout the entire estimation and prediction process, unlike most approaches that consist of multiple analysis stages.

Worked examples are presented in the \texttt{RISDM} package's vignette, as well as in [@fos23].

### Installation

The `RISDM` package can be installed using `devtools` R package.

```{r,eval=FALSE}
install.packages('devtools')
devtools::install_github( repo="Scott-Foster/RISDM", build_vignettes=FALSE)
```

## Funding

This work was part of The National Vertebrate Pests and Weeds Distribution project, which was partially funded by the Australian Government Department of Agriculture, Fisheries and Forestry’s Established Pest Animals and Weeds Management Pipeline Program and Supporting Communities Manage Pests and Weeds Program.

## Code of Conduct
  
Please note that the ppmData project is released with a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html). By contributing to this project, you agree to abide by its terms.

## Contributing Software
Fork the `RISDM` repository

Clone your fork using the command:

`git clone https://github.com/<username>/RISDM.git`

Contribute to your forked repository.

Create a pull request.

If your code passes the necessary checks and is documented, your changes 
and/or additions will be merged in the main `RISDM` repository.

## Reporting Bugs

If you notice an issue with this repository, please report it using [Github Issues](https://github.com/skiptoniam/RISDM/issues). When reporting an implementation bug, include a small example that helps to reproduce the error (a non-working minimal example). The issue will be addressed as quickly as possible.

## Seeking Support

If you have questions or need additional support, please open a [Github Issues](https://github.com/skiptoniam/RISDM/issues) or send a direct email to scott.foster@data61.csiro.au.


## References 


